-- INSERT INTO Person(id, name, city)
-- VALUES
-- (102, 'Sham', 'Mumbai'), 
-- (103, 'Paul', 'Chennai');
-- If you are providing a value to the all columns and in the sequence you dont have to write (id, name, city) this after a table name while inserting
-- INSERT INTO Person
-- VALUES 
-- (104, 'Alex', 'Pune');
-- selects all columns in table
-- SELECT * FROM person;

-- TO select specific column from the table do
-- SELECT name, city FROM person;